name: run-tests
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.9.0]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Set Node version ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - run: npm run test:e2e